# ==================
# Environment
# ==================
environment: production

# ==================
# Base
# ==================
url: "https://alexpate.uk"

# ==================
# Assets
# ==================
assets:
  compress:
    css: true
    js: true
  digest: true
  cdn: https://dn9zc8o6p92dz.cloudfront.net